language: python
python:
  - "2.7"
install:
  - "pip install --upgrade pip"
  - "pip install wheel"
  - "pip wheel . --process-dependency-links"
  - "pip install . --process-dependency-links"
script: dumpit2volatilityrc
